use_frameworks!

platform :ios, '8.0'

target 'AModule_Example' do
  pod 'AModule', :path => '../'

  target 'AModule_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
