use_frameworks!
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://github.com/yuekun91/KK_iOS.git'

platform :ios, '10.0'

target 'AModule_Example' do
  pod 'AModule', :path => '../'

  target 'AModule_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
